const data = {
  products: [
    {
      name: 'Nike Slim shirts',
      slug: 'nike-slim-shirt',
      Category: 'Shirts',
      image: '/image/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit shirt',
      slug: 'adidas-fit-shirt',
      Category: 'Shirts',
      image: '/image/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality shirt',
    },

    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      Category: 'Pants',
      image: '/image/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      Category: 'Pants',
      image: '/image/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};

export default data;
